#!/bin/bash
ar cru libtaichi_c_api_internal.a \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/operand.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/local_access_chain_convert_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_composites.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/name_mapper.o \
  build-taichi-ios-arm64/taichi/runtime/gfx/taichi.build/Debug-iphoneos/gfx_runtime.build/Objects-normal/arm64/snode_tree_manager.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/ir_builder.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_capability.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/extension.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_type.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/dead_variable_elimination.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/ext_inst.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_builtins.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/type_factory.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/remove_duplicates_pass.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/vulkan_device.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/flatten_decoration_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/snode_types.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_barriers.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/binary.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/constant_fold.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/local_single_block_elim_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/unreachable_code_elimination.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inst_buff_addr_check_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inst_bindless_check_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/eliminate_dead_functions_util.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_statements.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_peeling.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/remove_unused_interface_variables_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/make_block_local.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/extract_constant.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/demote_atomics.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/cfg.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/offloaded_task_type.o \
  build-taichi-ios-arm64/taichi/util/taichi.build/Debug-iphoneos/taichi_util.build/Objects-normal/arm64/str.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_cfg.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/type_check.o \
  build-taichi-ios-arm64/taichi/util/taichi.build/Debug-iphoneos/taichi_util.build/Objects-normal/arm64/offline_cache.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_image.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/vulkan_device_creator.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/simplify.o \
  build-taichi-ios-arm64/taichi/codegen/spirv/taichi.build/Debug-iphoneos/spirv_codegen.build/Objects-normal/arm64/spirv_ir_builder.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/type_utils.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_execution_limitations.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/fold.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/expr.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/loop_invariant_code_motion.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/offload.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/ccp_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/memory_pool.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/cache_loop_invariant_global_vars.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/folding_rules.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/spirv_optimizer_options.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/feature_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/cfg_cleanup_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/eliminate_dead_members_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_ray_query.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/die.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/construct.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/value_number_table.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/function.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/build_module.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/snode_rw_accessors_bank.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/assembly_grammar.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/timer.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/desc_sroa_util.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_immutable_local_vars.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/set_spec_constant_default_value_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/vector_dce.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/unified_allocator.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_adjacency.o \
  build-taichi-ios-arm64/taichi/runtime/gfx/taichi.build/Debug-iphoneos/gfx_runtime.build/Objects-normal/arm64/runtime.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/ir_node_extended_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/composite.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/dominator_tree.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/basic_block.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/compact_ids_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/ssa_rewrite_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/scalar_replacement_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/ir_loader.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/eliminate_immutable_local_vars.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/statement_usage_replace.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/module_loader.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/module_builder.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/debug_info_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/register_pressure.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/if_conversion.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/convert_to_half_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/mesh.o \
  build-taichi-ios-arm64/taichi/util/taichi.build/Debug-iphoneos/taichi_util.build/Objects-normal/arm64/lang_util.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/libspirv.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/private_to_local_pass.o \
  build-taichi-ios-arm64/taichi/runtime/gfx/taichi.build/Debug-iphoneos/gfx_runtime.build/Objects-normal/arm64/aot_module_loader_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/text.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/mem_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_small_type_uses.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_constants.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/insert_scratch_pad.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/kernel.o \
  build-taichi-ios-arm64/taichi/codegen/spirv/taichi.build/Debug-iphoneos/spirv_codegen.build/Objects-normal/arm64/spirv_types.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/snode_tree.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/bls_analyzer.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_c_api.build/Objects-normal/arm64/taichi_gfx_impl.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/lower_matrix_ptr.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/transform_statements.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/frontend_ir.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/table.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/texture.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/device.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/profiler.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/pass_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_mode_setting.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/utils.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/core.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_derivatives.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_scopes.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/remove_assume_in_range.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/program_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/spread_volatile_semantics.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/make_mesh_block_local.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/simplification_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/diagnostic.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/disassemble.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/instruction.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validation_state.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_c_api.build/Objects-normal/arm64/taichi_vulkan_impl.o \
  build-taichi-ios-arm64/taichi/util/taichi.build/Debug-iphoneos/taichi_util.build/Objects-normal/arm64/zip.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_fission.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/logging.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/check_fields_registered.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/ir.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/def_use_manager.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/virtual_dir.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_literals.o \
  build-taichi-ios-arm64/taichi/codegen/spirv/taichi.build/Debug-iphoneos/spirv_codegen.build/Objects-normal/arm64/spirv_codegen.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/desc_sroa.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_c_api.build/Objects-normal/arm64/taichi_metal_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/types.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/optimize_bit_struct_stores.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/callable.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/detect_read_only.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/lower_access.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/device_capability.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/fix_func_call_arguments.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/demote_no_access_mesh_fors.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/local_single_store_elim_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/binary_op_simplify.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/const_folding_rules.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/code_sink.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/fix_storage_class.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/combine_access_chains.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/optimizer.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/opcode.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/scalarize.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_fusion.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/enum_string_mapping.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/interp_fixup_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/cfg_optimization.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/basic_block.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_instruction.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/strip_nonsemantic_info_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/function.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_bitwise.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/offline_cache_util.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/cleanup.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/detect_fors_with_break.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/fold_spec_constant_op_and_composite_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/workaround1209.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_decorations.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/basic_stmt_visitor.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/replace_statements.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/ir_printer.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/alias_analysis.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/merge_return_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/control_flow_graph.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/extensions.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/eliminate_dead_constant_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_debug.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/instruction.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/value_diff.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/snode.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/instruction_list.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/same_statements.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/local_redundancy_elimination.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/spirv_endian.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/spirv_validator_options.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/convert_to_sampled_image_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inst_debug_printf_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/demote_dense_struct_fors.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/clone.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/vulkan_loader.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/zip.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_memory.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_snode_read_writes.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/statements.o \
  build-taichi-ios-arm64/taichi/util/taichi.build/Debug-iphoneos/taichi_util.build/Objects-normal/arm64/action_recorder.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/wrap_opkill.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/json.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/bit_loop_vectorize.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/auto_diff.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/timeline.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_dependence_helpers.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/struct_cfg_analysis.o \
  build-taichi-ios-arm64/taichi/common/taichi.build/Debug-iphoneos/taichi_common.build/Objects-normal/arm64/miniz.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_meshfor_relation_types.o \
  build-taichi-ios-arm64/taichi/runtime/program_impls/vulkan/taichi.build/Debug-iphoneos/vulkan_program_impl.build/Objects-normal/arm64/vulkan_program.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/data_source_analysis.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/freeze_spec_constant_value_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/ndarray.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/build_cfg.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/vulkan_memory_allocator.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_annotation.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inline_exhaustive_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_c_api.build/Objects-normal/arm64/taichi_core_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/unify_const_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/strength_reduction_pass.o \
  build-taichi-ios-arm64/taichi/codegen/spirv/taichi.build/Debug-iphoneos/spirv_codegen.build/Objects-normal/arm64/snode_struct_compiler.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/compile_to_offloads.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/parse_number.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/strip_debug_info_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/print.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/reverse_segments.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/constants.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_unroller.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/kernel_profiler.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_logicals.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/eliminate_dead_functions_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_atomics.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/replace_desc_array_access_using_var_index.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/graph_data.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_utils.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/relax_float_ops_pass.o \
  build-taichi-ios-arm64/taichi/runtime/gfx/taichi.build/Debug-iphoneos/gfx_runtime.build/Objects-normal/arm64/aot_module_builder_impl.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_id.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_fusion_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/check_out_of_bound.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gen_offline_cache_key.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/redundancy_elimination.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_primitives.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/demote_operations.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_misc.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/graphics_robust_access_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/interface_var_sroa.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/program.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/eliminate_dead_input_components_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/whole_kernel_cse.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_unswitch_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/dominator_analysis.o \
  build-taichi-ios-arm64/taichi/cache/gfx/taichi.build/Debug-iphoneos/gfx_cache.build/Objects-normal/arm64/cache_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/dead_insert_elim_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/verify.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/frontend_type_check.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/vulkan_api.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/instrument_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_function.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_memory_semantics.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_uniquely_accessed_pointers.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/type.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/remove_dontinline_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/aggressive_dead_code_elim_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/scalar_analysis.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/spirv_target_env.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/bit_vector.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/function.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/demote_mesh_statements.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/re_id.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_conversion.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/propagator.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/copy_prop_arrays.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/type_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/decoration_manager.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/scalar_analysis_simplification.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/module.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/upgrade_memory_model.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/scalar_pointer_lowerer.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/lower_ast.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/block_merge_pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/remove_loop_unique.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_non_uniform.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/text_handler.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_layout.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_arithmetics.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/snode_expr_utils.o \
  build-taichi-ios-arm64/taichi/rhi/vulkan/taichi.build/Debug-iphoneos/vulkan_rhi.build/Objects-normal/arm64/spirv_reflect.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/ir_context.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_dependence.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/alg_simp.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/amd_ext_to_khr.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_extensions.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inline_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/reduce_load_size.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_mesh_thread_local.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/validate_interfaces.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/parsed_operand.o \
  build-taichi-ios-arm64/taichi/codegen/spirv/taichi.build/Debug-iphoneos/spirv_codegen.build/Objects-normal/arm64/kernel_utils.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/determine_ad_stack_size.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/flag_access.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/mesh_bls_analyzer.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/dynamic_loader.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/licm_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/taichi.build/Debug-iphoneos/SPIRV-Tools-static.build/Objects-normal/arm64/string_utils.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/block_merge_util.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/loop_descriptor.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/stmt_op_types.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/function_key.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/inline_opaque_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/dead_branch_elim_pass.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/pass.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/make_thread_local.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/compile_config.o \
  build-taichi-ios-arm64/external/SPIRV-Tools/source/opt/taichi.build/Debug-iphoneos/SPIRV-Tools-opt.build/Objects-normal/arm64/replace_invalid_opc.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/arch.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/make_mesh_thread_local.o \
  build-taichi-ios-arm64/taichi.build/Debug-iphoneos/taichi_core.build/Objects-normal/arm64/gather_deactivations.o
libtool -static -o build-taichi-ios-arm64/install/c_api/lib/libtaichi_c_api.a libtaichi_c_api_internal.a /Users/penguinliong/Library/Developer/Xcode/DerivedData/MoltenVK-gzvhtkjichuwfkckzndbkobvsjbr/Build/Products/Release-iphoneos/libMoltenVK.a
rm libtaichi_c_api_internal.a